-- Find actual table names in SUSDB
USE SUSDB
GO

PRINT 'All tables in SUSDB:'
SELECT TABLE_NAME 
FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_TYPE = 'BASE TABLE'
ORDER BY TABLE_NAME
GO

PRINT ''
PRINT 'Tables that might contain Classification info:'
SELECT TABLE_NAME 
FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_NAME LIKE '%Class%'
ORDER BY TABLE_NAME
GO

PRINT ''
PRINT 'Tables that might contain Target Group info:'
SELECT TABLE_NAME 
FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_NAME LIKE '%Target%' OR TABLE_NAME LIKE '%Group%'
ORDER BY TABLE_NAME
GO
