-- Find actual column names in key tables
USE SUSDB
GO

PRINT 'Columns in tbCategory:'
SELECT COLUMN_NAME, DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'tbCategory'
ORDER BY ORDINAL_POSITION
GO

PRINT ''
PRINT 'Sample data from tbCategory:'
SELECT TOP 5 *
FROM tbCategory
GO

PRINT ''
PRINT 'Columns in tbUpdate:'
SELECT COLUMN_NAME, DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'tbUpdate'
ORDER BY ORDINAL_POSITION
GO

PRINT ''
PRINT 'Columns in tbKBArticleForRevision:'
SELECT COLUMN_NAME, DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'tbKBArticleForRevision'
ORDER BY ORDINAL_POSITION
GO

PRINT ''
PRINT 'Columns in tbLocalizedPropertyForRevision:'
SELECT COLUMN_NAME, DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'tbLocalizedPropertyForRevision'
ORDER BY ORDINAL_POSITION
GO
